"""empty message

Revision ID: 0003 Add created_at to tables
Revises: 0002 Insert event_types and fees
Create Date: 2017-12-14 09:40:06.095101

"""

# revision identifiers, used by Alembic.
revision = '0003 Add created_at to tables'
down_revision = '0002 Insert event_types and fees'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_types', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('fees', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column(u'event_types', 'event_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column(u'fees', 'valid_from',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fees', 'created_at')
    op.drop_column('events', 'created_at')
    op.drop_column('event_types', 'created_at')
    op.alter_column(u'fees', 'valid_from',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column(u'event_types', 'event_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
