"""empty message

Revision ID: 0005 Add speakers table
Revises: 0004 Add token_blacklist table
Create Date: 2018-01-22 23:50:13.462361

"""

# revision identifiers, used by Alembic.
revision = '0005 Add speakers table'
down_revision = '0004 Add token_blacklist table'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speakers',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('speakers')
    # ### end Alembic commands ###
