"""empty message

Revision ID: 0010 add venues.old_id
Revises: 0009 add venues table/upd ev dt
Create Date: 2018-07-28 23:57:46.229443

"""

# revision identifiers, used by Alembic.
revision = '0010 add venues.old_id'
down_revision = '0009 add venues table/upd ev dt'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('old_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'old_id')
    # ### end Alembic commands ###
