"""empty message

Revision ID: 0011 update events model
Revises: 0010 add venues.old_id
Create Date: 2018-08-11 00:18:58.695721

"""

# revision identifiers, used by Alembic.
revision = '0011 update events model'
down_revision = '0010 add venues.old_id'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('conc_fee', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('fee', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('multi_day_conc_fee', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('multi_day_fee', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('speaker_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.alter_column('events', 'event_type_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'events', 'event_types', ['event_type_id'], ['id'])
    op.create_foreign_key(None, 'events', 'speakers', ['speaker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.alter_column('events', 'event_type_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_column('events', 'speaker_id')
    op.drop_column('events', 'multi_day_fee')
    op.drop_column('events', 'multi_day_conc_fee')
    op.drop_column('events', 'fee')
    op.drop_column('events', 'conc_fee')
    # ### end Alembic commands ###
