"""empty message

Revision ID: 0014 add speaker parent_id
Revises: 0013 add speaker id event dates
Create Date: 2018-09-22 15:12:58.857385

"""

# revision identifiers, used by Alembic.
revision = '0014 add speaker parent_id'
down_revision = '0013 add speaker id event dates'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speakers', sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_column('speakers', 'alternate_names')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speakers', sa.Column('alternate_names', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('speakers', 'parent_id')
    # ### end Alembic commands ###
