"""empty message

Revision ID: 0015 add event_date_to_speaker
Revises: 0014 add speaker parent_id
Create Date: 2018-11-03 00:27:46.213841

"""

# revision identifiers, used by Alembic.
revision = '0015 add event_date_to_speaker'
down_revision = '0014 add speaker parent_id'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_date_to_speaker',
    sa.Column('event_date_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('speaker_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['event_date_id'], ['event_dates.id'], ),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], ),
    sa.UniqueConstraint('event_date_id', 'speaker_id', name='uix_event_date_id_to_speaker_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_date_to_speaker')
    # ### end Alembic commands ###
