"""empty message

Revision ID: 0016 FK nullable event_id
Revises: 0015 add event_date_to_speaker
Create Date: 2018-11-03 15:11:39.429692

"""

# revision identifiers, used by Alembic.
revision = '0016 FK nullable event_id'
down_revision = '0015 add event_date_to_speaker'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_dates', 'event_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'event_dates', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_dates', type_='foreignkey')
    op.alter_column('event_dates', 'event_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
