"""empty message

Revision ID: 0017 drop speaker_id from events
Revises: 0016 FK nullable event_id
Create Date: 2018-11-03 15:24:57.630460

"""

# revision identifiers, used by Alembic.
revision = '0017 drop speaker_id from events'
down_revision = '0016 FK nullable event_id'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'event_dates_speaker_id_fkey', 'event_dates', type_='foreignkey')
    op.drop_column('event_dates', 'speaker_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_dates', sa.Column('speaker_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'event_dates_speaker_id_fkey', 'event_dates', 'speakers', ['speaker_id'], ['id'])
    # ### end Alembic commands ###
