"""empty message

Revision ID: 0018 add duration and venue_id
Revises: 0017 drop speaker_id from events
Create Date: 2018-11-06 22:19:33.741802

"""

# revision identifiers, used by Alembic.
revision = '0018 add duration and venue_id'
down_revision = '0017 drop speaker_id from events'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('venue_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'events', 'venues', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'venue_id')
    op.drop_column('events', 'duration')
    # ### end Alembic commands ###
