"""empty message

Revision ID: 0019 add articles
Revises: 0018 add duration and venue_id
Create Date: 2018-11-24 14:54:09.364415

"""

# revision identifiers, used by Alembic.
revision = '0019 add articles'
down_revision = '0018 add duration and venue_id'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('old_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(u'event_dates', 'venue_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'event_dates', 'venue_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_table('articles')
    # ### end Alembic commands ###
