"""empty message

Revision ID: 0022 add end time to event_date
Revises: 0021 allow access_area nullable
Create Date: 2019-03-17 23:26:48.400945

"""

# revision identifiers, used by Alembic.
revision = '0022 add end time to event_date'
down_revision = '0021 allow access_area nullable'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_dates', sa.Column('end_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_dates', 'end_time')
    # ### end Alembic commands ###
