"""empty message

Revision ID: 0026 add expires, send_starts_at
Revises: 0025 add email and email types
Create Date: 2019-07-16 00:30:24.998868

"""

# revision identifiers, used by Alembic.
revision = '0026 add expires, send_starts_at'
down_revision = '0025 add email and email types'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('expires', sa.DateTime(), nullable=True))
    op.add_column('emails', sa.Column('send_starts_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'send_starts_at')
    op.drop_column('emails', 'expires')
    # ### end Alembic commands ###
