"""empty message

Revision ID: 81b2645f1397
Revises: 0026 add expires, send_starts_at
Create Date: 2019-07-21 00:23:24.304597

"""

# revision identifiers, used by Alembic.
revision = '0027 add email_state'
down_revision = '0026 add expires, send_starts_at'

from alembic import op
import sqlalchemy as sa

from app.models import EMAIL_STATES


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_states',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )

    for state in EMAIL_STATES:
        op.execute(
            "INSERT INTO email_states (name) VALUES ('{}')".format(state)
        )

    op.add_column(u'emails', sa.Column('email_state', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_emails_email_state'), 'emails', ['email_state'], unique=False)
    op.create_foreign_key(None, 'emails', 'email_states', ['email_state'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_index(op.f('ix_emails_email_state'), table_name='emails')
    op.drop_column(u'emails', 'email_state')
    op.drop_table('email_states')
    # ### end Alembic commands ###
