"""empty message

Revision ID: 0028 add task_id to emails
Revises: 0027 add email_state
Create Date: 2019-08-07 00:42:19.093405

"""

# revision identifiers, used by Alembic.
revision = '0028 add task_id to emails'
down_revision = '0027 add email_state'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('task_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'task_id')
    # ### end Alembic commands ###
