"""empty message

Revision ID: 0029 add marketings model
Revises: 0028 add task_id to emails
Create Date: 2019-08-10 16:02:36.970386

"""

# revision identifiers, used by Alembic.
revision = '0029 add marketings model'
down_revision = '0028 add task_id to emails'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketings',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('old_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('old_id'),
    sa.UniqueConstraint('description')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marketings')
    # ### end Alembic commands ###
