"""empty message

Revision ID: 0031 add email_to_member
Revises: 0030 add members model
Create Date: 2019-08-14 00:40:29.304333

"""

# revision identifiers, used by Alembic.
revision = '0031 add email_to_member'
down_revision = '0030 add members model'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_to_member',
    sa.Column('email_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('member_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('email_id', 'member_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_to_member')
    # ### end Alembic commands ###
